//
//  AABridge.h
//  AABridge
//
//  Created by onekiloparsec on 25/12/2019.
//  Copyright © 2019 onekiloparsec. All rights reserved.
//

// Note: This is the public header used when building a static library (i.e., with SPM). Imports should be done
// in the "Header.h" style.

#include "PlatformHelpers.h"
#include "KPCAASwiftAdditions.h"

#include "KPCAA2DCoordinate.h"
#include "KPCAA3DCoordinate.h"
#include "KPCAAAberration.h"
#include "KPCAAAngularSeparation.h"
#include "KPCAABinaryStar.h"
#include "KPCAACoordinateTransformation.h"
#include "KPCAADate.h"
#include "KPCAADiameters.h"
#include "KPCAADynamicalTime.h"
#include "KPCAAEarth.h"
#include "KPCAAEclipses.h"
#include "KPCAAEclipticalElements.h"
#include "KPCAAElementsPlanetaryOrbit.h"
#include "KPCAAElliptical.h"
#include "KPCAAEquationOfTime.h"
#include "KPCAAEquinoxesAndSolstices.h"
#include "KPCAAFK5.h"
#include "KPCAAGalileanMoons.h"
#include "KPCAAGlobe.h"
#include "KPCAAIlluminatedFraction.h"
#include "KPCAAInterpolate.h"
#include "KPCAAJupiter.h"
#include "KPCAAKepler.h"
#include "KPCAAMars.h"
#include "KPCAAMercury.h"
#include "KPCAAMoon.h"
#include "KPCAAMoonIlluminatedFraction.h"
#include "KPCAAMoonMaxDeclinations.h"
#include "KPCAAMoonNodes.h"
#include "KPCAAMoonPerigeeApogee.h"
#include "KPCAAMoonPhases.h"
#include "KPCAANearParabolic.h"
#include "KPCAANeptune.h"
#include "KPCAANodes.h"
#include "KPCAANutation.h"
#include "KPCAAParabolic.h"
#include "KPCAAParallactic.h"
#include "KPCAAParallax.h"
#include "KPCAAPhysicalJupiter.h"
#include "KPCAAPhysicalMars.h"
#include "KPCAAPhysicalMoon.h"
#include "KPCAAPhysicalSun.h"
#include "KPCAAPlanetPerihelionAphelion.h"
#include "KPCAAPlanetaryPhenomena.h"
#include "KPCAAPluto.h"
#include "KPCAAPrecession.h"
#include "KPCAARefraction.h"
#include "KPCAARiseTransitSet.h"
#include "KPCAASaturn.h"
#include "KPCAASaturnMoons.h"
#include "KPCAASaturnRings.h"
#include "KPCAASidereal.h"
#include "KPCAAStellarMagnitudes.h"
#include "KPCAASun.h"
#include "KPCAAUranus.h"
#include "KPCAAVenus.h"
